### ISSUE TITLE
yo one small problem

### ISSUE THREAD

**Issue by SLINK465** [KNaiskes/gmailBot#1]
i set up everything nice and dandy but, how do i start this whole thing? i made many attempts to figure it out but i can't figure it out. how do you start it??

**Comment by knaiskes** [comment]
Hello,

In order to start it you have to run the following command from your terminal (you must be in the same directory as the project).
`python main.py`

If it works, please let me know so I can update the README file.

**Comment by knaiskes** [comment]
https://github.com/KNaiskes/gmailBot/commit/1df526a64e8ffbf9c41bd02ba15689cad76ebc5b
